dist: xenial
language: python
python:
 - "3.6"
 - "3.7"
install:
 - pip install --upgrade pip setuptools
 - pip install ".[test]"
script:
 - pylint monoloco --disable=unused-variable,fixme
 - pytest -v
